name:                Symbolics
version:             0.1.0.0
github:              "garvagarwal/Symbolics"
license:             BSD3
author:              "Garv Agarwal"
maintainer:          "agarwalg2000@gmail.com"
copyright:           "2021 Garv Agarwal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/garvagarwal/Symbolics#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Symbolics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Symbolics

tests:
  Symbolics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Symbolics
